server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#      defaultZone: http://172.22.171.50:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: productservice
          uri: http://localhost:9000
          predicates:
            - Path=/api/product/**
#          filters:
#            - AuthFilter
        - id: userservice
          uri: http://localhost:9001
          predicates:
            - Path=/api/user/**
#          filters:
#            - AuthFilter
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


